# Numpy

Common variables

In [4]:
import numpy as np

# Numpy Arrays

In [5]:
a = np.array([1, 2, 3])
b = np.array([[1, 3, 4], [2, 4, 6]])
c = np.array([[3.14, 6.0, 9], [1, 2, 4]], dtype=float)

print(a)
print(b)
print(c)

[1 2 3]
[[1 3 4]
 [2 4 6]]
[[3.14 6.   9.  ]
 [1.   2.   4.  ]]


# Numpy Data types
- np.int
- np.float
- np.int64
- np.float32
- np.complex   # Complex numbers
- np.bool
- np.object    # Python object
- np.string_   # Fixed-length string
- np.unicode_  # Fixed-length unicode


# Numpy placeholders

In [14]:
d = np.zeros([2, 3])
e = np.ones([4, 2, 2])
f = np.arange(100, 500, 10)
g = np.random.random([10, 10])
h = np.empty([5, 5])

print(d)
print(e)
print(f)
print(g)
print(h)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270
 280 290 300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450
 460 470 480 490]
[[0.70179532 0.49982629 0.89109087 0.5459987  0.31999866 0.18663034
  0.97263829 0.23041897 0.29289552 0.47838425]
 [0.03528195 0.49027999 0.31377514 0.17059903 0.72980675 0.23946801
  0.15516655 0.47968793 0.40625225 0.98961269]
 [0.35172379 0.31815093 0.58101308 0.59388003 0.48985341 0.75754285
  0.13905392 0.1135824  0.47846364 0.84622311]
 [0.27107667 0.46941884 0.9850125  0.85859591 0.75195731 0.80484786
  0.94944461 0.63881671 0.1114873  0.41963066]
 [0.66544341 0.50244529 0.4795803  0.91009443 0.24451745 0.38669167
  0.13109466 0.78848087 0.49062312 0.36614859]
 [0.8686527  0.0124802  0.06484851 0.18130198 0.577334   0.00776841
  0.34644156 0.60116566 0.44577319 0.35100146]
 [0.47589192 0.01592331 0.9948510

# Numpy information/interspection

In [17]:
print(e)
print(e.shape)
print(len(e))
print(e.ndim)
print(e.size)
print(e.dtype)
print(g.astype(int))


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
(4, 2, 2)
4
3
16
float64
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


# numpy operations

In [ ]:
i = np.array([[1, 2, 3], [4, 6, 8]])
j = np.array([[10, -10, 3], [1, 100, -20]])

print(i + j)
print(i - j)
print(i * j)
print(i / j)
print(np.add(i, j))
print(np.subtract(i, j))
print(np.exp(i))   # exponentiation
print(np.sqrt(i))  # sqrt
print(np.sin(i))   
print(np.cos(i))
print(np.log(i))   # natural logarithm

[[ 11  -8   6]
 [  5 106 -12]]
[[ -9  12   0]
 [  3 -94  28]]
[[  10  -20    9]
 [   4  600 -160]]
[[ 0.1  -0.2   1.  ]
 [ 4.    0.06 -0.4 ]]
[[ 11  -8   6]
 [  5 106 -12]]
[[ -9  12   0]
 [  3 -94  28]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 4.03428793e+02 2.98095799e+03]]
[[1.         1.41421356 1.73205081]
 [2.         2.44948974 2.82842712]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.2794155   0.98935825]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.96017029 -0.14550003]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.79175947 2.07944154]]


In [26]:
k = np.ones([10, 10])
k = k * 123
print(k)

[[123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]
 [123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]
 [123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]
 [123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]
 [123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]
 [123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]
 [123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]
 [123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]
 [123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]
 [123. 123. 123. 123. 123. 123. 123. 123. 123. 123.]]


In [ ]:
l = np.eye(10)   # identity matrix
print(l)

m = np.random.random(10)
print(m.dot(l))  # dot product

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[0.80446648 0.03107313 0.88408187 0.64870586 0.09755086 0.95792865
 0.36072873 0.62450785 0.73590648 0.4101269 ]


# numpy comparisons

In [36]:
print(i)
print(j)

# Elementwise comparisons
print(i == j)
print(i != j)
print(i < 4)

# Arraywise comparison
print(np.array_equal(i, j))
print(np.array_equal(i, i))

[[1 2 3]
 [4 6 8]]
[[ 10 -10   3]
 [  1 100 -20]]
[[False False  True]
 [False False False]]
[[ True  True False]
 [ True  True  True]]
[[ True  True  True]
 [False False False]]
False
True


Indexing

In [43]:
print(i)
print(j)

mask = np.array([
    [True, False, True],
    [False, False, True]
], dtype=bool)
print(mask)
print(i[mask])

print(i == j)
print(i[i == j])

[[1 2 3]
 [4 6 8]]
[[ 10 -10   3]
 [  1 100 -20]]
[[ True False  True]
 [False False  True]]
[1 3 8]
[[False False  True]
 [False False False]]
[3]


In [53]:
print(i)
print(i[1][2])
print(i[1, 2])

# array slicing
print(i[1:])

# comparison (elements less than 4) then mask
print(i[i <= 4])

print(np.transpose(i))
print(np.ravel(i))

[[1 2 3]
 [4 6 8]]
8
8
[[4 6 8]]
[1 2 3 4]
[[1 4]
 [2 6]
 [3 8]]
[1 2 3 4 6 8]


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [62]:
m = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
n = m.reshape(5, 2)
print(m)
print(n)

m = np.append(m, np.array([11, 12]))
print(m)
o = m.reshape(4, 3, 1)
print(o)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


# Assigment by reference/value

In [66]:
p = np.array([1, 2, 3])
p[1] = 30
print(p)

# by reference
q = p
q[1] = 100
print(p)

r = p.copy()
r[1] = -2
print(p)
print(r)

[ 1 30  3]
[  1 100   3]
[  1 100   3]
[ 1 -2  3]


# Saving and Loading

In [ ]:
with open("numpy_data.npy", "wb") as file:
    np.save(file, p)
    np.save(file, q)

In [68]:
with open("numpy_data.npy", "rb") as file:
    s = np.load(file)
    t = np.load(file)

print(s)
print(t)

[  1 100   3]
[  1 100   3]
